# Generated by Django 4.2.11 on 2024-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posttopic_alter_posttag_options_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='posts', to='posts.posttopic', verbose_name='Рубрики'),
        ),
    ]
