# Generated by Django 4.2.11 on 2024-05-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posttopic_is_general_alter_post_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': 'Публікація', 'verbose_name_plural': '🟩 Публікації'},
        ),
        migrations.AddField(
            model_name='post',
            name='ReviewRating',
            field=models.PositiveSmallIntegerField(blank=True, max_length=100, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='post',
            name='review_minuses',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Мінуси'),
        ),
        migrations.AddField(
            model_name='post',
            name='review_pluses',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Плюси'),
        ),
    ]
