# Generated by Django 4.2.11 on 2024-05-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options_post_reviewrating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date',), 'verbose_name': 'Публікація', 'verbose_name_plural': '🟩 Публікації'},
        ),
        migrations.AlterField(
            model_name='post',
            name='ReviewRating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
