# Generated by Django 4.2.11 on 2024-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_options_alter_post_reviewrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': 'Публікація', 'verbose_name_plural': '🟩 Публікації'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_date'], 'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AlterModelOptions(
            name='posttag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='posttopic',
            options={'ordering': ['name'], 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'ordering': ['created_date'], 'verbose_name': 'Тип публікації', 'verbose_name_plural': 'Типи публікацій'},
        ),
        migrations.AlterField(
            model_name='post',
            name='is_publicated',
            field=models.BooleanField(choices=[(False, 'Чернетка'), (True, 'Опубліковано')], default=True, verbose_name='Опубліковано'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_date', 'slug'], name='posts_created_ac414f_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['-created_date'], name='comments_created_a61b54_idx'),
        ),
    ]
