# Generated by Django 4.2.11 on 2024-05-21 18:15

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_options_alter_postcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, unique_for_date='created_date', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=1000, verbose_name='Текст'),
        ),
    ]
