# Generated by Django 4.2.11 on 2024-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_reviewrating_post_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг огляду'),
        ),
    ]
