# Generated by Django 4.2.11 on 2024-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
    ]
