# Generated by Django 4.2.11 on 2024-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_postcomment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/%Y/%m/%d/detail/', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/posts/%Y/%m/%d/', verbose_name='Зображення'),
        ),
    ]
