# Generated by Django 4.2.11 on 2024-05-27 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_alter_post_detail_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL, verbose_name='Мінуси'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='Плюси'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Мінуси'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Плюси'),
        ),
        migrations.AlterField(
            model_name='post',
            name='review_minuses',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Огляд (Мінуси)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='review_pluses',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Огляд (Плюси)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='review_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Огляд (Рейтинг)'),
        ),
    ]
