# Generated by Django 4.1.13 on 2024-06-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postcomment_dislikes_postcomment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review_minuses',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Мінуси (Огляд)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='review_pluses',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Плюси (Огляд)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='review_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг (Огляд)'),
        ),
    ]
