# Generated by Django 4.2.11 on 2024-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthday_date_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/avatar', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_bg',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/profile_bg', verbose_name='Фон'),
        ),
    ]
