# Generated by Django 4.2.11 on 2024-05-24 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_alter_user_profile_bg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined'], 'verbose_name': 'Користувач', 'verbose_name_plural': '🔴 Користувачі'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_bg',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Опис профілю')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UA', verbose_name='Номер телефону')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_path, verbose_name='Аватар')),
                ('profile_bg', models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_bg_path, verbose_name='Фон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': '🟥 Профілі',
                'db_table': 'profiles',
                'ordering': ['user__date_joined'],
            },
        ),
    ]
