# Generated by Django 4.2.11 on 2024-06-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscribe_profile_following_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['-created_date'], 'verbose_name': 'Підписка', 'verbose_name_plural': 'Підписки'},
        ),
        migrations.RenameIndex(
            model_name='subscribe',
            new_name='subscriptio_created_bf3967_idx',
            old_name='users_subsc_created_dc43c6_idx',
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table='subscriptions',
        ),
    ]
