# Generated by Django 4.2.11 on 2024-06-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_subscribe_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('user_from', 'user_to')},
        ),
    ]
