services:
    web:
        container_name: game-news-django
        build: .
        command: gunicorn src.core.wsgi:application --bind 0.0.0.0:8024 --preload --workers 4 --threads 4 --env DJANGO_SETTINGS_MODULE=src.core.settings.local
        volumes:
            - static_content:/app/staticfiles
            - media_content:/app/media
        ports:
            - 8030:8030
        depends_on:
            - db
            - redis
        env_file: ./.env

    db:
        container_name: game-news-postgres
        image: postgres:16.3-alpine3.20
        restart: always
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - 5434:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: ./.env.database

    redis:
        container_name: game-news-redis
        image: redis:alpine
        command: redis-server --appendonly yes
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis_data:/root/redis
            - /home/user/redis/redis.conf:/usr/local/etc/redis/redis.conf
        env_file: ./.env.redis

    celery:
        container_name: game-news-celery
        build:
            context: .
        command: >
            sh -c "celery -A core.celery worker --pool=solo --loglevel=info"
        volumes:
            - .:/app
        depends_on:
            - redis
            - db
        env_file: ./.env

    nginx:
        container_name: game-news-nginx
        build: ./nginx
        ports:
            - 1338:8000
        volumes:
            - static_content:/app/staticfiles
        depends_on:
            - web

volumes:
    static_content:
    media_content:
    postgres_data:
    redis_data:
