# Generated by Django 4.2.11 on 2024-05-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Назва')),
                ('description', models.CharField(max_length=300, verbose_name='Опис оголошення')),
                ('css_style', models.TextField(blank=True, default='', max_length=600, verbose_name='Стилі (CSS)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisement_images', verbose_name='Зображення')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('disable_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Коли вимкнути')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'db_table': 'site_announcements',
                'ordering': ('-created_date',),
            },
        ),
    ]
