# Generated by Django 4.2.11 on 2025-05-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': 'Публікація', 'verbose_name_plural': 'Публікації'},
        ),
    ]
